-- Create tables inside PostgreSQL TimescaleDB database `weather`
-- for holding data read via RTL-SDR antenna from a Bresser 5-in-1 weather station

-- Table is written to every 12 seconds
-- time,id/location,Battery,Temperature,Humidity,Wind Gust,Wind Speed,Direction,Rain
CREATE TABLE weather_station_metrics (
   time          TIMESTAMPTZ  NOT NULL, -- time in the following format: "2024-07-20 14:44:52"
   location      CHARACTER(5) NULL,     -- either 'bshed' for bike shed or 'bport' for bike port or 'gshed' for garden shed or whatever
   id            NUMERIC(8)   NULL,     -- the station ID that is randomly generated by outer sensor every time the battery is replaced, e.g. 41326225, i.e. 8 digits long
   battery_ok    SMALLINT     NULL,     -- is probably 1 if battery is OK, 0 if battery is not OK
   temperature_C REAL         NULL,     -- temperature in degrees Celsius
   humidity      REAL         NULL,     -- relative humidity in percent
   wind_max_m_s  REAL         NULL,     -- also called "Wind Gust"
   wind_avg_m_s  REAL         NULL,     -- also called "Wind Speed"
   wind_dir_deg  SMALLINT     NULL,     -- wind direction in degrees: North = 0, East = 90, South = 180, West = 270
   rain_mm       REAL         NULL      -- amount of rain fallen since weather station was deployed (cumulative)
);

-- Convert tables to TimescaleDB hypertables:
SELECT create_hypertable('weather_station_metrics', 'time');