-- Create tables inside PostgreSQL TimescaleDB database `h64`

-- Table with values changing slowly, enough to update only every 15 minutes
CREATE TABLE inverter_slow (
   time                          TIMESTAMPTZ NOT NULL,
   battery_soc                   REAL        NULL,
   battery_soh                   REAL        NULL,
   daily_pv_production           REAL        NULL,
   total_pv_production           REAL        NULL,
   daily_load_energy_consumption REAL        NULL,
   total_load_energy_consumption REAL        NULL,
   daily_energy_bought           REAL        NULL,
   daily_energy_sold             REAL        NULL,
   total_energy_bought           REAL        NULL,
   total_energy_sold             REAL        NULL,
   daily_battery_charge          REAL        NULL,
   daily_battery_discharge       REAL        NULL,
   total_battery_charge          REAL        NULL,
   total_battery_discharge       REAL        NULL,
   daily_battery_life_cycles     REAL        NULL,
   total_battery_life_cycles     REAL        NULL,
   daily_losses                  REAL        NULL,
   total_losses                  REAL        NULL,
   battery_temperature           REAL        NULL,
   dc_temperature                REAL        NULL,
   temperature                   REAL        NULL
);

-- Table with values changing fast, about every second. Table is updated about every 5 seconds (update interval of the Home Assistant solarman integration)
CREATE TABLE inverter_fast (
   time             TIMESTAMPTZ NOT NULL,
   grid_power       REAL        NULL,
   load_power       REAL        NULL,
   load_l1_power    REAL        NULL,
   load_l2_power    REAL        NULL,
   load_l3_power    REAL        NULL,
   battery_power    REAL        NULL,
   pv1_power        REAL        NULL,
   pv2_power        REAL        NULL,
   power_losses     REAL        NULL
);

-- Convert tables to TimescaleDB hypertables:
SELECT create_hypertable('inverter_slow', 'time');
SELECT create_hypertable('inverter_fast', 'time');




-- Create tables inside PostgreSQL TimescaleDB database `h64`
-- for holding data from a heat pump, e.g. from the power meter

-- Table is written to upon every pulse of the heat pump power meter (one pulse every 0.001 kWh)
CREATE TABLE heat_pump (
   time  TIMESTAMPTZ NOT NULL, -- time in the following format: "2024-11-18 20:28:16"
   power REAL        NULL
);

-- Convert tables to TimescaleDB hypertables:
SELECT create_hypertable('heat_pump', 'time');





-- Create tables inside PostgreSQL TimescaleDB database `h64`
-- for holding data read via RTL-SDR antenna from a Bresser 5-in-1 weather station

-- Table is written to every 12 seconds
-- time,id/location,Battery,Temperature,Humidity,Wind Gust,Wind Speed,Direction,Rain
CREATE TABLE weather_station (
   time          TIMESTAMPTZ  NOT NULL, -- time in the following format: "2024-07-20 14:44:52"
   location      CHARACTER(5) NULL,     -- either 'bshed' for bike shed or 'bport' for bike port or 'gshed' for garden shed or whatever
   id            NUMERIC(8)   NULL,     -- the station ID that is randomly generated by outer sensor every time the battery is replaced, e.g. 41326225, i.e. 8 digits long
   battery_ok    SMALLINT     NULL,     -- is probably 1 if battery is OK, 0 if battery is not OK
   temperature_C REAL         NULL,     -- temperature in degrees Celsius
   humidity      REAL         NULL,     -- relative humidity in percent
   wind_max_m_s  REAL         NULL,     -- also called "Wind Gust"
   wind_avg_m_s  REAL         NULL,     -- also called "Wind Speed"
   wind_dir_deg  SMALLINT     NULL,     -- wind direction in degrees: North = 0, East = 90, South = 180, West = 270
   rain_mm       REAL         NULL      -- amount of rain fallen since weather station was deployed (cumulative)
);

-- Convert tables to TimescaleDB hypertables:
SELECT create_hypertable('weather_station', 'time');